[package]
name = "pyo3"
version = "0.1.0"
description = "Bindings to Python"
authors = ["PyO3 Project and Contributors <https://github.com/PyO3"]
readme = "README.md"
keywords = [
    "pyo3",
    "python",
]
homepage = "https://github.com/pyo3/pyo3"
repository = "https://github.com/pyo3/pyo3.git"
documentation = "http://pyo3.github.io/pyo3/doc/pyo3/"
categories = ["api-bindings", "development-tools::ffi"]
license = "MIT/APACHE-2"
exclude = [
    ".gitignore",
    ".travis.yml",
    ".cargo/config",
    "appveyor.yml",
]
build = "build.rs"

[dependencies]
libc = "0.2"
num-traits = "0.1"
pyo3cls = { path = "pyo3cls" }

[build-dependencies]
regex = "0.1"

[features]
default = ["nightly"]

# Enable additional features that require nightly rust
nightly = []

# Use this feature when building an extension module.
# It tells the linker to keep the python symbols unresolved,
# so that the module can also be used with statically linked python interpreters.
extension-module = []
